"use client";

import { useState, useRef, useCallback } from "react";

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

type Severity = "low" | "medium" | "high" | "critical";

interface Flaw {
  title: string;
  severity: Severity;
  description: string;
  question: string;
}

interface CriticPassResult {
  lens: string;
  summary: string;
  flaws: Flaw[];
}

type LensState =
  | { status: "idle" }
  | { status: "running" }
  | { status: "done"; result: CriticPassResult }
  | { status: "error"; reason: string };

type LensId =
  | "pre_mortem"
  | "unit_economics"
  | "adversarial_competitor"
  | "execution_risk";

// ─────────────────────────────────────────────
// Export helpers
// ─────────────────────────────────────────────

function critiqueToPlainText(
  lensStates: Record<LensId, LensState>,
  lenses: typeof LENSES
): string {
  const lines: string[] = ["VERIDEX CRITIQUE", "═".repeat(60), ""];
  for (const lens of lenses) {
    const state = lensStates[lens.id];
    if (state.status !== "done") continue;
    const r = state.result;
    lines.push(`${lens.tag} · ${lens.label.toUpperCase()}`);
    lines.push("─".repeat(40));
    lines.push(r.summary);
    lines.push("");
    for (const flaw of r.flaws) {
      lines.push(`[${flaw.severity.toUpperCase()}] ${flaw.title}`);
      lines.push(flaw.description);
      lines.push(`→ ${flaw.question}`);
      lines.push("");
    }
    lines.push("");
  }
  lines.push(`Generated by Veridex · veridex.fyi`);
  return lines.join("\n");
}

function critiqueToMarkdown(
  lensStates: Record<LensId, LensState>,
  lenses: typeof LENSES
): string {
  const lines: string[] = ["# Veridex Critique", ""];
  for (const lens of lenses) {
    const state = lensStates[lens.id];
    if (state.status !== "done") continue;
    const r = state.result;
    lines.push(`## ${lens.label}`);
    lines.push(`> ${r.summary}`);
    lines.push("");
    for (const flaw of r.flaws) {
      lines.push(`### \`${flaw.severity.toUpperCase()}\` ${flaw.title}`);
      lines.push(flaw.description);
      lines.push("");
      lines.push(`**Key question:** ${flaw.question}`);
      lines.push("");
    }
  }
  lines.push("---");
  lines.push("*Generated by [Veridex](https://veridex.fyi)*");
  return lines.join("\n");
}

// ─────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────

const LENSES: { id: LensId; tag: string; label: string; description: string }[] = [
  { id: "pre_mortem",            tag: "LENS 01", label: "Pre-Mortem",            description: "18 months from now — it failed. Reconstruct why." },
  { id: "unit_economics",        tag: "LENS 02", label: "Unit Economics",        description: "Does the math actually work at every stage?" },
  { id: "adversarial_competitor",tag: "LENS 03", label: "Adversarial Competitor",description: "You're a well-funded rival. How do you kill this?" },
  { id: "execution_risk",        tag: "LENS 04", label: "Execution Risk",        description: "What's most likely to break in shipping?" },
];

const SEV: Record<Severity, { badge: string; border: string; qbg: string; dot: string }> = {
  low:      { badge: "text-white/40 bg-white/5 border-white/10",          border: "border-white/[0.07]",    qbg: "bg-white/[0.025]",      dot: "bg-white/25" },
  medium:   { badge: "text-yellow-400 bg-yellow-400/10 border-yellow-400/20", border: "border-yellow-400/10",   qbg: "bg-yellow-400/[0.04]",  dot: "bg-yellow-400" },
  high:     { badge: "text-orange-400 bg-orange-400/10 border-orange-400/20", border: "border-orange-400/10",   qbg: "bg-orange-400/[0.04]",  dot: "bg-orange-400" },
  critical: { badge: "text-red-400 bg-red-400/10 border-red-400/20",      border: "border-red-400/10",      qbg: "bg-red-400/[0.04]",     dot: "bg-red-400" },
};

const SEV_ORDER: Severity[] = ["critical", "high", "medium", "low"];

// ─────────────────────────────────────────────
// Small helpers
// ─────────────────────────────────────────────

function sevRank(s: Severity) { return SEV_ORDER.indexOf(s); }

function Divider() {
  return <div className="border-t border-white/[0.06]" />;
}

function Tag({ children }: { children: React.ReactNode }) {
  return (
    <span className="text-[10px] font-bold uppercase tracking-[0.16em] text-white/30">
      {children}
    </span>
  );
}

// ─────────────────────────────────────────────
// Flaw card
// ─────────────────────────────────────────────

function FlawCard({ flaw }: { flaw: Flaw }) {
  const s = SEV[flaw.severity];
  return (
    <div className={`rounded-xl border ${s.border} bg-white/[0.02] overflow-hidden`}>
      <div className="px-4 pt-4 pb-3 space-y-2">
        <div className="flex items-start gap-3 justify-between">
          <p className="text-[13px] font-semibold text-white/90 leading-snug flex-1">{flaw.title}</p>
          <span className={`shrink-0 mt-0.5 rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${s.badge}`}>
            {flaw.severity}
          </span>
        </div>
        <p className="text-[12px] text-white/45 leading-relaxed">{flaw.description}</p>
      </div>
      <div className={`border-t ${s.border} ${s.qbg} px-4 py-3`}>
        <p className="text-[11px] text-white/55 font-medium leading-relaxed">
          <span className="text-white/20 mr-1.5">→</span>{flaw.question}
        </p>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────
// Lens panel
// ─────────────────────────────────────────────

function LensPanel({ lens, state }: { lens: typeof LENSES[number]; state: LensState }) {
  const [open, setOpen] = useState(false);
  const isDone    = state.status === "done";
  const isRunning = state.status === "running";
  const isError   = state.status === "error";
  const isIdle    = state.status === "idle";

  const critCount = isDone ? state.result.flaws.filter(f => f.severity === "critical").length : 0;
  const highCount = isDone ? state.result.flaws.filter(f => f.severity === "high").length : 0;
  const total     = isDone ? state.result.flaws.length : 0;

  return (
    <div
      className={`rounded-2xl border transition-all duration-200 ${
        isDone    ? "border-white/10 bg-[#111] cursor-pointer hover:border-white/[0.15]"
        : isRunning ? "border-white/10 bg-[#0f0f0f]"
        : isError   ? "border-red-500/20 bg-[#0f0f0f]"
        : "border-white/[0.06] bg-[#0c0c0c]"
      }`}
      onClick={() => isDone && setOpen(o => !o)}
    >
      {/* Header row */}
      <div className="flex items-center justify-between px-6 py-5">
        <div className="flex items-center gap-4">
          <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-white/[0.04] border border-white/[0.07] shrink-0">
            {isRunning ? <span className="w-1.5 h-1.5 rounded-full bg-white/50 animate-pulse" />
              : isDone   ? <span className="w-1.5 h-1.5 rounded-full bg-white/60" />
              : isError  ? <span className="w-1.5 h-1.5 rounded-full bg-red-400" />
              : <span className="w-1.5 h-1.5 rounded-full bg-white/15" />}
          </div>
          <div>
            <Tag>{lens.tag}</Tag>
            <p className={`font-semibold text-[15px] leading-tight mt-0.5 ${isIdle ? "text-white/30" : "text-white/90"}`}>
              {lens.label}
            </p>
            <p className={`text-[11px] mt-0.5 ${isIdle ? "text-white/15" : "text-white/35"}`}>
              {lens.description}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          {isRunning && <span className="text-[11px] text-white/30 italic">Analyzing…</span>}
          {isError   && <span className="text-[11px] text-red-400/70">Failed</span>}
          {isDone && (
            <>
              {critCount > 0 && <span className="rounded-full bg-red-400/10 border border-red-400/20 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-red-400">{critCount} critical</span>}
              {highCount > 0 && <span className="rounded-full bg-orange-400/10 border border-orange-400/20 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-orange-400">{highCount} high</span>}
              <span className="text-[11px] text-white/25 font-mono ml-1">{total} flaws</span>
              <span className="text-white/20 text-[13px] ml-2 select-none">{open ? "↑" : "↓"}</span>
            </>
          )}
        </div>
      </div>

      {/* Expanded */}
      {isDone && open && (
        <>
          <Divider />
          <div className="px-6 py-5 border-b border-white/[0.06]">
            <Tag>Summary</Tag>
            <p className="mt-2 text-[13px] text-white/55 leading-relaxed">{state.result.summary}</p>
          </div>
          <div className="px-6 py-5 space-y-3">
            <Tag>Findings</Tag>
            <div className="space-y-3 mt-2">
              {[...state.result.flaws]
                .sort((a, b) => sevRank(a.severity) - sevRank(b.severity))
                .map((flaw, i) => <FlawCard key={i} flaw={flaw} />)}
            </div>
          </div>
        </>
      )}

      {isError && "reason" in state && (
        <>
          <Divider />
          <div className="px-6 py-4">
            <p className="text-[11px] text-red-400/60">{state.reason}</p>
          </div>
        </>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────
// Landing sections
// ─────────────────────────────────────────────

function Hero({ onTry }: { onTry: () => void }) {
  return (
    <section className="pt-20 pb-24 border-b border-white/[0.06]">
      <div className="mx-auto max-w-3xl px-6 space-y-8">
        {/* Badge */}
        <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-3 py-1.5">
          <span className="h-1 w-1 rounded-full bg-white/40" />
          <span className="text-[10px] font-bold uppercase tracking-[0.18em] text-white/40">Veridex · veridex.fyi</span>
        </div>

        {/* Headline */}
        <div className="space-y-4">
          <h1 className="text-[28px] sm:text-[32px] font-semibold leading-tight tracking-[-0.02em] text-white max-w-xl">
            Before you present your strategy, break it.
          </h1>
          <p className="text-[14px] text-white/45 leading-relaxed max-w-lg">
            Veridex stress-tests your thinking — exposing blind spots, weak logic, and execution risks in minutes. Four independent AI critics. No flattery.
          </p>
        </div>

        {/* CTAs */}
        <div className="flex items-center gap-3">
          <button
            onClick={onTry}
            className="rounded-xl bg-white px-6 py-3 text-[13px] font-semibold text-black hover:opacity-90 active:scale-[0.98] transition-all"
          >
            Try Veridex free
          </button>
          <a
            href="#how-it-works"
            className="rounded-xl border border-white/10 px-6 py-3 text-[13px] font-semibold text-white/60 hover:text-white hover:border-white/20 transition-all"
          >
            See how it works
          </a>
        </div>

        {/* Social proof strip */}
        <p className="text-[11px] text-white/20 font-medium">
          No account required · Runs in ~30 seconds · Your document is sent to OpenAI for analysis and is not stored on our servers.
        </p>
      </div>
    </section>
  );
}

function ProblemSection() {
  const items = [
    "Hidden assumptions go unchecked until it's too late",
    "Weak logic survives internal reviews — nobody wants to be the critic",
    "No one plays the role of a truly adversarial reviewer",
    "AI tools generate ideas and validate them — they don't challenge them",
  ];
  return (
    <section className="py-20 border-b border-white/[0.06]">
      <div className="mx-auto max-w-3xl px-6">
        <Tag>The problem</Tag>
        <h2 className="mt-3 text-[28px] sm:text-[32px] font-semibold leading-tight tracking-[-0.02em] text-white max-w-lg">
          Most strategies don't fail because they're bad. They fail because they're untested.
        </h2>
        <div className="mt-8 grid gap-3">
          {items.map((item, i) => (
            <div key={i} className="flex items-start gap-3 rounded-xl border border-white/[0.06] bg-white/[0.02] px-5 py-4">
              <span className="mt-0.5 h-1.5 w-1.5 shrink-0 rounded-full bg-white/20" />
              <p className="text-[13px] text-white/55 leading-relaxed">{item}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function HowItWorks() {
  const steps = [
    { n: "01", title: "Paste your strategy", body: "Drop in your strategy doc, pitch, or plan. No formatting required — raw thinking is fine." },
    { n: "02", title: "Four critics analyze in parallel", body: "Pre-Mortem, Unit Economics, Adversarial Competitor, and Execution Risk all run simultaneously in ~30 seconds." },
    { n: "03", title: "Get a structured critique", body: "Each lens returns a summary, ranked flaws by severity, and the sharpest question you need to answer next." },
  ];
  return (
    <section id="how-it-works" className="py-20 border-b border-white/[0.06]">
      <div className="mx-auto max-w-3xl px-6">
        <Tag>How it works</Tag>
        <h2 className="mt-3 text-[28px] sm:text-[32px] font-semibold leading-tight tracking-[-0.02em] text-white">
          Veridex acts as your strategy red-team.
        </h2>
        <div className="mt-10 grid gap-4">
          {steps.map((s) => (
            <div key={s.n} className="flex gap-6 rounded-2xl border border-white/[0.06] bg-[#111] px-6 py-5">
              <span className="text-[28px] font-bold text-white/[0.07] leading-none shrink-0 font-mono">{s.n}</span>
              <div>
                <p className="font-semibold text-[14px] text-white/85">{s.title}</p>
                <p className="mt-1 text-[12px] text-white/40 leading-relaxed">{s.body}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function LensPreview() {
  const lenses = [
    {
      tag: "LENS 01", label: "Pre-Mortem", severity: "critical" as Severity,
      summary: "The strategy assumes enterprise buyers will move fast based on an introductory call. That assumption has a 90% fail rate.",
      flaw: "No defined sales cycle length", question: "What evidence do you have that enterprise procurement moves in under 60 days for a new vendor category?",
    },
    {
      tag: "LENS 02", label: "Unit Economics", severity: "high" as Severity,
      summary: "Cost-to-serve is understated. LLM inference at current volumes doesn't support the $29/mo price point at gross margin.",
      flaw: "CAC not modeled against stated channels", question: "What is your blended CAC via Twitter/LinkedIn and how many months does it take to recover?",
    },
    {
      tag: "LENS 03", label: "Adversarial Competitor", severity: "high" as Severity,
      summary: "Any well-funded player ships a 'critique mode' toggle in their existing product. That neutralizes your entire differentiation in one sprint.",
      flaw: "Differentiation is feature-level, not structural", question: "What do you have that a $500M ARR competitor cannot copy in 6 weeks?",
    },
    {
      tag: "LENS 04", label: "Execution Risk", severity: "medium" as Severity,
      summary: "A solo founder with a 4-week timeline is implying a scope that would take a team of three 3 months.",
      flaw: "Timeline implies incorrect capacity", question: "Which two features are you willing to cut to ship a working v1 in 4 weeks?",
    },
  ];

  return (
    <section className="py-20 border-b border-white/[0.06]">
      <div className="mx-auto max-w-3xl px-6">
        <Tag>Example output</Tag>
        <h2 className="mt-3 text-[28px] sm:text-[32px] font-semibold leading-tight tracking-[-0.02em] text-white max-w-lg">
          This is what a real critique looks like.
        </h2>
        <p className="mt-2 text-[13px] text-white/35">Actual output on: "AI tool for consultants. $29/mo. 4-week launch. Growth via Twitter."</p>

        <div className="mt-8 space-y-3">
          {lenses.map((l) => {
            const s = SEV[l.severity];
            return (
              <div key={l.tag} className="rounded-2xl border border-white/10 bg-[#111] overflow-hidden">
                <div className="flex items-center gap-4 px-6 py-4 border-b border-white/[0.06]">
                  <div className="flex items-center justify-center w-7 h-7 rounded-lg bg-white/[0.04] border border-white/[0.07] shrink-0">
                    <span className="w-1.5 h-1.5 rounded-full bg-white/60" />
                  </div>
                  <div>
                    <Tag>{l.tag}</Tag>
                    <p className="text-[14px] font-semibold text-white/85 mt-0.5">{l.label}</p>
                  </div>
                  <span className={`ml-auto rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${s.badge}`}>
                    {l.severity}
                  </span>
                </div>
                <div className="px-6 py-4 space-y-3">
                  <p className="text-[12px] text-white/45 leading-relaxed">{l.summary}</p>
                  <div className={`rounded-xl border ${s.border} ${s.qbg} px-4 py-3`}>
                    <p className="text-[11px] font-semibold text-white/60 mb-1">{l.flaw}</p>
                    <p className="text-[11px] text-white/40 leading-relaxed">
                      <span className="text-white/20 mr-1">→</span>{l.question}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

function DiffTable() {
  const rows = [
    { label: "Generates ideas",       them: true,  us: false },
    { label: "Challenges assumptions",them: false, us: true  },
    { label: "Agrees with your prompt",them: true, us: false },
    { label: "Finds structural flaws", them: false, us: true },
    { label: "Surface-level responses",them: true, us: false },
    { label: "Ranked, structured critique",them: false, us: true },
    { label: "General-purpose",       them: true,  us: false },
    { label: "Strategy-specific lenses",them: false,us: true },
  ];

  return (
    <section className="py-20 border-b border-white/[0.06]">
      <div className="mx-auto max-w-3xl px-6">
        <Tag>Differentiation</Tag>
        <h2 className="mt-3 text-[28px] sm:text-[32px] font-semibold leading-tight tracking-[-0.02em] text-white">
          Built to challenge, not just generate.
        </h2>
        <p className="mt-2 text-[13px] text-white/35 max-w-md">
          ChatGPT will help you refine your strategy. Veridex will tell you where it breaks.
        </p>

        <div className="mt-8 rounded-2xl border border-white/10 bg-[#111] overflow-hidden">
          {/* Table header */}
          <div className="grid grid-cols-3 border-b border-white/[0.06] px-5 py-3">
            <p className="text-[11px] font-bold uppercase tracking-widest text-white/20 col-span-1" />
            <p className="text-[11px] font-bold uppercase tracking-widest text-white/20 text-center">Typical AI</p>
            <p className="text-[11px] font-bold uppercase tracking-widest text-white/60 text-center">Veridex</p>
          </div>
          {rows.map((row, i) => (
            <div
              key={i}
              className={`grid grid-cols-3 items-center px-5 py-3.5 ${i < rows.length - 1 ? "border-b border-white/[0.04]" : ""}`}
            >
              <p className="text-[12px] text-white/50 col-span-1">{row.label}</p>
              <p className="text-center text-[13px]">{row.them ? <span className="text-white/20">✓</span> : <span className="text-white/[0.12]">—</span>}</p>
              <p className="text-center text-[13px]">{row.us   ? <span className="text-white/80">✓</span> : <span className="text-white/[0.12]">—</span>}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function CtaBanner({ onTry }: { onTry: () => void }) {
  return (
    <section className="py-20 border-b border-white/[0.06]">
      <div className="mx-auto max-w-3xl px-6 text-center space-y-6">
        <h2 className="text-[28px] sm:text-[32px] font-semibold leading-tight tracking-[-0.02em] text-white">
          Run your first strategy critique.
        </h2>
        <p className="text-[14px] text-white/35 max-w-sm mx-auto leading-relaxed">
          No account. No setup. Paste your doc and get four independent critiques in about 30 seconds.
        </p>
        <button
          onClick={onTry}
          className="rounded-xl bg-white px-8 py-3.5 text-[13px] font-semibold text-black hover:opacity-90 active:scale-[0.98] transition-all"
        >
          Try Veridex free
        </button>
        <p className="text-[11px] text-white/20">Your document is sent to OpenAI for analysis and not stored by Veridex.</p>
      </div>
    </section>
  );
}

// ─────────────────────────────────────────────
// Export bar
// ─────────────────────────────────────────────

function ExportBar({ lensStates }: { lensStates: Record<LensId, LensState> }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    const text = critiqueToPlainText(lensStates, LENSES);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for browsers that block clipboard without HTTPS
      const el = document.createElement("textarea");
      el.value = text;
      el.style.position = "fixed";
      el.style.opacity = "0";
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [lensStates]);

  const handleDownload = useCallback(() => {
    const md = critiqueToMarkdown(lensStates, LENSES);
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `veridex-critique-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [lensStates]);

  return (
    <div className="flex items-center justify-between rounded-2xl border border-white/[0.06] bg-[#0f0f0f] px-6 py-4">
      <div>
        <p className="text-[12px] font-semibold text-white/60">Export critique</p>
        <p className="text-[11px] text-white/25 mt-0.5">Copy to clipboard or download as Markdown</p>
      </div>
      <div className="flex items-center gap-2">
        <button
          onClick={handleCopy}
          className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2 text-[12px] font-semibold text-white/70 transition-all hover:bg-white/[0.07] hover:text-white active:scale-[0.97]"
        >
          {copied ? (
            <><span className="text-green-400">✓</span> Copied</>
          ) : (
            <><span className="text-white/30">⎘</span> Copy</>
          )}
        </button>
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2 text-[12px] font-semibold text-white/70 transition-all hover:bg-white/[0.07] hover:text-white active:scale-[0.97]"
        >
          <span className="text-white/30">↓</span> Download .md
        </button>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────
// Product (critique tool)
// ─────────────────────────────────────────────

function CritiqueProduct() {
  const [doc, setDoc] = useState("");
  const [lensStates, setLensStates] = useState<Record<LensId, LensState>>({
    pre_mortem:             { status: "idle" },
    unit_economics:         { status: "idle" },
    adversarial_competitor: { status: "idle" },
    execution_risk:         { status: "idle" },
  });
  const [running, setRunning]     = useState(false);
  const [done, setDone]           = useState(false);
  const abortRef                  = useRef<AbortController | null>(null);

  function updateLens(id: LensId, state: LensState) {
    setLensStates(prev => ({ ...prev, [id]: state }));
  }

  async function runCritique() {
    if (!doc.trim() || doc.trim().length < 20 || running) return;

    setRunning(true);
    setDone(false);
    for (const l of LENSES) updateLens(l.id, { status: "idle" });

    const abort = new AbortController();
    abortRef.current = abort;

    const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";

    try {
      const res = await fetch(`${apiUrl}/api/v1/critique/stream`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ strategy_doc: doc }),
        signal: abort.signal,
      });

      if (!res.ok || !res.body) throw new Error(`HTTP ${res.status}`);

      const reader  = res.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      while (true) {
        const { done: streamDone, value } = await reader.read();
        if (streamDone) break;
        buffer += decoder.decode(value, { stream: true });

        const parts = buffer.split("\n\n");
        buffer = parts.pop() ?? "";

        for (const part of parts) {
          const lines = part.split("\n");
          let event = "", data = "";
          for (const line of lines) {
            if (line.startsWith("event: ")) event = line.slice(7).trim();
            if (line.startsWith("data: "))  data  = line.slice(6).trim();
          }
          if (!event || !data) continue;

          let payload: any;
          try { payload = JSON.parse(data); } catch { continue; }

          if      (event === "pass_started")   updateLens(payload.lens as LensId, { status: "running" });
          else if (event === "pass_completed") updateLens(payload.lens as LensId, { status: "done", result: payload.result as CriticPassResult });
          else if (event === "error")          updateLens(payload.lens as LensId, { status: "error", reason: payload.reason });
          else if (event === "done")           setDone(true);
        }
      }
    } catch (err: any) {
      if (err.name !== "AbortError") console.error("Stream error:", err);
    } finally {
      setRunning(false);
    }
  }

  const anyResults      = LENSES.some(l => lensStates[l.id].status !== "idle");
  const completedCount  = LENSES.filter(l => ["done","error"].includes(lensStates[l.id].status)).length;

  return (
    <section id="product" className="py-20">
      <div className="mx-auto max-w-3xl px-6 space-y-8">
        {/* Section header */}
        <div>
          <Tag>Run a critique</Tag>
          <h2 className="mt-3 text-[28px] sm:text-[32px] font-semibold leading-tight tracking-[-0.02em] text-white">
            Paste your strategy. Get four critics.
          </h2>
        </div>

        {/* Input card */}
        <div className="rounded-2xl border border-white/10 bg-[#111] overflow-hidden">
          <div className="px-6 pt-5 pb-4 border-b border-white/[0.06]">
            <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-white/30 mb-1">Strategy Document</p>
            <p className="text-[14px] font-semibold text-white/80">Describe what you're building</p>
            <p className="text-[11px] text-white/25 mt-0.5">Include: product, audience, pricing, growth strategy, and what makes it defensible.</p>
          </div>
          <div className="px-6 py-5">
            <textarea
              value={doc}
              onChange={e => setDoc(e.target.value.slice(0, 10000))}
              maxLength={10000}
              placeholder={"Example:\n\nWe're building a $20/month AI tool that critiques startup strategy docs. Target: solo founders. Launch in 4 weeks. Growth via founder Twitter. Defensibility: proprietary critique framework."}
              className="w-full h-40 resize-none bg-transparent text-[13px] text-white/80 placeholder-white/15 outline-none leading-relaxed"
            />
          </div>
          <div className="flex items-center justify-between px-6 py-4 border-t border-white/[0.06] bg-white/[0.015]">
            <span className="text-[11px] text-white/20 font-mono">
              {doc.length > 0 ? `${doc.length.toLocaleString()} / 10,000 chars` : "min. 20 chars"}
            </span>
            <button
              onClick={runCritique}
              disabled={running || doc.trim().length < 20}
              className="flex items-center gap-2 rounded-xl bg-white px-5 py-2.5 text-[13px] font-semibold text-black transition-all disabled:opacity-25 hover:opacity-90 active:scale-[0.98]"
            >
              {running
                ? <><span className="w-1.5 h-1.5 rounded-full bg-black/40 animate-pulse" />Analyzing…</>
                : "Run critique"}
            </button>
          </div>
        </div>

        {/* Progress bar */}
        {anyResults && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Tag>{running ? "Running four lenses in parallel" : done ? "Critique complete" : "Finishing…"}</Tag>
              <p className="text-[11px] text-white/25 font-mono">{completedCount}&nbsp;/&nbsp;{LENSES.length}</p>
            </div>
            <div className="h-px w-full bg-white/[0.06] rounded-full overflow-hidden">
              <div
                className="h-px bg-white/40 rounded-full transition-all duration-500 ease-out"
                style={{ width: `${(completedCount / LENSES.length) * 100}%` }}
              />
            </div>
          </div>
        )}

        {/* Lens panels */}
        {anyResults && (
          <div className="space-y-3">
            {LENSES.map(lens => (
              <LensPanel key={lens.id} lens={lens} state={lensStates[lens.id]} />
            ))}
          </div>
        )}

        {/* Export actions — only shown when at least one lens is done */}
        {done && completedCount > 0 && (
          <ExportBar lensStates={lensStates} />
        )}
      </div>
    </section>
  );
}

// ─────────────────────────────────────────────
// Footer
// ─────────────────────────────────────────────

function Footer() {
  return (
    <footer className="border-t border-white/[0.06] py-8">
      <div className="mx-auto max-w-3xl px-6 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="h-1 w-1 rounded-full bg-white/30" />
          <span className="text-[11px] font-bold uppercase tracking-[0.16em] text-white/25">Veridex</span>
        </div>
        <p className="text-[11px] text-white/20">veridex.fyi</p>
      </div>
    </footer>
  );
}

// ─────────────────────────────────────────────
// Page
// ─────────────────────────────────────────────

export default function Page() {
  function scrollToProduct() {
    document.getElementById("product")?.scrollIntoView({ behavior: "smooth" });
  }

  return (
    <main className="min-h-screen text-white" style={{ background: "#0a0a0a", fontFamily: "var(--font-geist-sans)" }}>
      <Hero onTry={scrollToProduct} />
      <ProblemSection />
      <HowItWorks />
      <LensPreview />
      <DiffTable />
      <CtaBanner onTry={scrollToProduct} />
      <CritiqueProduct />
      <Footer />
    </main>
  );
}
